nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:8081']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': ~
